version: '3'

services:
  api:
    image: linkextractor-api:step5-python
    build: ./api
    depends_on:
      - redis
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - wordpress_network
  web:
    image: linkextractor-web:step5-php
    depends_on:
      - api
    build: ./www
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://api:5000/api/
    networks:
      - wordpress_network

  redis:
    image: redis
    networks:
      - wordpress_network

  locust:
    image: locustio/locust
    depends_on:
      - web
    command: -f /mnt/locust/locustfile.py  --master
    ports:
      - "8089:8089"
    volumes:
      - ./locust-task:/mnt/locust

    environment:
      - LOCUST_HOST=http://web:80
    networks:
      - wordpress_network

  worker:
    image: locustio/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host=locust
    volumes:
      - ./locust-task:/mnt/locust
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge
