version: '3.8'

services:
  nginx:
    image: nginx:1.19.0
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - wordpress-data:/usr/share/nginx/html
    depends_on:
      - api
      - web

  api:
    image: linkextractor-api:python
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379

  web:
    image: linkextractor-web:php
    build: ./www
    ports:
      - "8080:80"
    environment:
      - API_ENDPOINT=http://api:5000/api/

  redis:
    image: redis

  locust:
    container_name: locust
    image: grubykarol/locust
    environment:
      - ATTACKED_HOST=http://nginx:80
      - LOCUST_OPTS=-r 10 -u 10
    volumes:
      - .:/locust
    ports:
      - "8089:8089"

volumes:
  wordpress-data:


